### ISSUE TITLE
[Error] 'read' not found, aborting.

### ISSUE THREAD

**Issue by sheriffed3** [GalacticFog/gestalt-k8s-install#3]
Hi,
I tried to install gestalt-platform for Docker CE for Desktop with Kubernetes but have got error.
`$ ./install-gestalt-platform docker-for-desktop.conf

Checking environment...

[Error] 'read' not found, aborting.`

I don't understand what exactly happens. Can you help me?
The file diagnostics.log in attached.
 
[diagnostics.log](https://github.com/GalacticFog/gestalt-k8s-install/files/2170664/diagnostics.log)

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

The installer is trying to check that several supporting commands (including `read`) are present on your system.

I think you've encountered two bugs:
  - the installer tries to check that a 'read' command is present on your system using `which read`, but I suspect the check isn't valid on systems where `read` is implemented as a shell function rather than a separate binary.  
  - Also, I see from the diagnostics.log that `bc` doesn't seem to be present on your system from inspecting the diagnostics.log.

I just made a commit to the repo that removes the check for `read` and also adds a check for `bc`.  Could you pull the latest from this repo and try again?  Please let me know how it goes.

Thanks,
Eric

**Comment by sheriffed3** [comment]
Right now all right. Thank you.
